@baseUrl = http://localhost:3000

### Try to login an unknow user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"unknown",
    "password":"admin"
}

### Create the manager user
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "firstname": "Jhon",
    "lastname": "Doe",
    "email":"jhon.doe@example.com",
    "password":"test"
}

### Login the manager user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "email":"jhon.doe@example.com",
    "password":"test"
}

### Login the manager user
POST {{baseUrl}}/trips/createtrip
Content-Type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJlbW1lcnkwMkBob3RtYWlsLmNvbSIsImlhdCI6MTcwMTYyNTc4MSwiZXhwIjoxNzg4MDI1NzgxfQ.28eU_UmDaFSAdY3f92laEjgZakPp5VgpopFLyf5XdIA

{
    "countryCode": "Belgium",
    "startDate": "2023-12-03",
    "endDate": "2023-12-10"
}
