@baseUrl = http://localhost:3000

### Trips Does nothing
GET http://localhost:3000/trips

### Read trip identified by 45
GET {{baseUrl}}/trips/1

### Read trips identified for user
GET {{baseUrl}}/trips/user/admin@where2go.com

### Read all possible places
GET {{baseUrl}}/trips/places/all

### Create one trip
POST {{baseUrl}}/trips/createtrip
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imp1bGllbi5yZW1tZXJ5QHN0dWRlbnQudmluY2kuYmUiLCJpYXQiOjE3MDI2NTQxMTIsImV4cCI6MTc4OTA1NDExMn0.H77Ve5mAweaTT_fVjk69PmA9uiApw8vv2mQEGHzQ1Vs

{
    "countryCode": "Belgium",
    "startDate": "2023-12-15",
    "endDate": "2023-12-20"
}

### Add one place to a trip
POST {{baseUrl}}/trips/addplace
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imp1bGllbi5yZW1tZXJ5QHN0dWRlbnQudmluY2kuYmUiLCJpYXQiOjE3MDI2NTQxMTIsImV4cCI6MTc4OTA1NDExMn0.H77Ve5mAweaTT_fVjk69PmA9uiApw8vv2mQEGHzQ1Vs

{
    "placeId": "ChIJbw4IMIbEw0cRLdRsNbreMSI",
    "tripId": "1"
}

### Remove one place of a trip
POST {{baseUrl}}/trips/removeplace
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imp1bGllbi5yZW1tZXJ5QHN0dWRlbnQudmluY2kuYmUiLCJpYXQiOjE3MDI2NTQxMTIsImV4cCI6MTc4OTA1NDExMn0.H77Ve5mAweaTT_fVjk69PmA9uiApw8vv2mQEGHzQ1Vs

{
    "placeId": "ChIJbw4IMIbEw0cRLdRsNbreMSI",
    "tripId": "1"
}